# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a03b98c6ee9037859527d125f53ebf76c6d36460b1249dbb5579b05ee50ef92930334639d8bb482255e7e6c2831a473365b8a388b6ab4d223492ea90b0f5db2

test:
  secret_key_base: 6afa5bc3f594309f033758cacaecac761bbcd3ad8239c889e281cfb3ea2760ed2ac3fd0a22a516a20fe604c5434f857f6bed0401f396a49e21eb439690164c97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
